### ISSUE TITLE
Swords Dance TM not working 

### ISSUE THREAD

**Issue by Deckersche** [Cobblemon-Islands/Bugs-And-Issues#100]
Feature: Sword Dance TM

Expected Behaviour: rightlclicking applies Swordsdance on pokemon that can learn it 

Current Behaviour: rightclicking does not apply the move to the pokemon

**Comment by DZtheCasual** [comment]
Keep in mind I believe our TMs are based off Gen 7
There is also an already reported bug of dropping a TM breaking it if this is related to that
