### ISSUE TITLE
Galarian Koffing doesnt evolve

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#114]
Feature: [Regional Pokemon (Galarian Koffing)]

Expected Behaviour: [evolves into Galarian Weezing]

Current Behaviour: [does not evolve]

Video Recordings/Screenshots: [(like a sir)]
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/fabe0c6c-fa5d-4a12-b152-2c1afcafe418)

How to reproduce the bug: []

**Comment by V-lpen** [comment]
fixed in next update
