### ISSUE TITLE
Kleavor does not learn stone axe

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#115]
Feature: [Pokemon Natural Moves]

Expected Behaviour: [Kleavor learn Stone Axe upon evolution from Scizor]

Current Behaviour: [move missing entirely, (not be added yet)]

Video Recordings/Screenshots: []
![Screenshot_20240225_180001_Discord.jpg](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/375e88a0-821e-4f23-b140-256a0a354a21)

How to reproduce the bug: []

**Comment by V-lpen** [comment]
fixed in next update
