### ISSUE TITLE
Monferno learns moves that Infernape does not

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#116]
Feature: [cobblemon movesets]

Expected Behaviour: [infernape to be able to learn Aura Sphere and Nasty Plot]

Current Behaviour: [Monferno can learn, but Infernape can not learn these moves, should be able to. ]

Screenshots:
![Screenshot_20240227_092729_Discord](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/6433870c-07b1-4631-bcc9-4515c993dc83)

How to reproduce the bug: []

**Comment by V-lpen** [comment]
Monferno nor Infernape do not learn these TMs in the moveset generation Cobblemon uses. 
Sorry! We will have to wait until Cobblemon adds it.
