### ISSUE TITLE
Galar Cursola shiny texture bugged

### ISSUE THREAD

**Issue by MrZeroxtz** [Cobblemon-Islands/Bugs-And-Issues#119]
Galar Cursola shiny texture bugged. Instead of turning it's shiny colors (black and white with purple eyes) it turned yellow and faceless.

![tgdxhhonti041](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149621522/f2f5c00d-74d9-47fd-a7b5-49e09b177996)
![2024-02-27_09 33 39](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149621522/4e942c35-642b-411b-a3f0-b8ea6c6d23fa)

**Comment by V-lpen** [comment]
fixed in next update!
