### ISSUE TITLE
Vikavolt shiny model not changing

### ISSUE THREAD

**Issue by MrZeroxtz** [Cobblemon-Islands/Bugs-And-Issues#121]
User changed vikavolt to shiny via pokebuilder. the shint particles appear but the model colors do no change.

![200px-HOME0738_s](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149621522/5af15bb0-839c-4146-b166-51c28b8230ca)
![image2](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149621522/9940f5c7-6cc2-4568-b844-88aedae30ca7)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149621522/32fbdb67-f0c3-4c63-a421-d9bcbcedee9a)

**Comment by V-lpen** [comment]
Fixed in the next update!
