### ISSUE TITLE
Minecraft Volcarona crash error

### ISSUE THREAD

**Issue by Undertoone** [Cobblemon-Islands/Bugs-And-Issues#126]
Feature : Game/Server

Expected behaviour : -

Current behaviour : game crash whenever a Volcarona is near

Screenshot : 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/163048410/49d4ba91-9f0e-4f2e-8304-eb88a79539a0)

How to reproduce the bug : I don't know

**Comment by V-lpen** [comment]
was an extra RP pack issue
