### ISSUE TITLE
Item clear countdown not working

### ISSUE THREAD

**Issue by Maxello1** [Cobblemon-Islands/Bugs-And-Issues#13]
Feature: Item clear
Expected Behaviour: Shows a countdown/timer before clearing items
Current Behaviour:  Does not show a countdown/timer before clearing ground items.
Video Recordings/Screenshots:
Additional Notes: Moon realm for sure. not tested in star and sun. (might already be fixed and not updated on TRELLO)

**Comment by Adainish** [comment]
Config needs fixing if this hasn't been looked at yet, @Furq07

**Comment by Furqit** [comment]
Should be fixed.
