### ISSUE TITLE
Metagross can't learn Psychic Fangs

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#132]
Feature: [Cobblemon Moves]

Expected Behaviour: [Metagross to be able to learn Psychic Fangs]

Current Behaviour: [Players have reported it can't learn Psychic Fangs, but it is on the list]

Video Recordings/Screenshots: []
[metagross.json](https://github.com/Cobblemon-Islands/Bugs-And-Issues/files/14611965/metagross.json)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/f60bff11-f638-4d91-8126-8e1398287e61)

How to reproduce the bug: []

**Comment by V-lpen** [comment]
closing this, as this is gen9 moveset.
