### ISSUE TITLE
Mega Blaziken Texture issue

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#152]
@V-lpen Requested to submit this

Mega Blaziken's talons only visible from one angle

![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/8f64fe47-8332-4655-9f9d-d211b1dcd1e3)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/9a3e18f1-d9e2-4705-927b-bf7f37fa062c)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/a4066715-fe6a-4aaf-a7cd-16fda657e8b6)

**Comment by V-lpen** [comment]
fixed ages ago, forgot to close
