### ISSUE TITLE
Some custom furniture do not drop upon breaking

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#19]
Feature: [Custom Furniture]

Expected Behaviour: [Item drops upon being destroyed]

Current Behaviour: [When the player destroys the furniture to move/relocate, the item doesnt drop]

Behavior reported by user, affected items are Wooden Ruins 2 and Ruins Statues.
No invisible barrier issue noted.
(Needs further testing/confirmation/replicate issue)

Video: 

https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/f258471c-785d-4cf5-9be2-d609a4789718

**Comment by Furqit** [comment]
This is fixed!
