### ISSUE TITLE
/observe battle doesn't work

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#21]
Feature: /observebattle command

Expected Behaviour: Using command alongside a battling player lets you watch moves used/etc

Current Behaviour: Using said command either reads as invalid or presents a broken menu.

<img width="509" alt="Screenshot 2023-11-04 at 3 17 56 PM" src="https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/f2c4ab2c-a68e-40a9-9fb0-e4f217141aa0">

**Comment by Adainish** [comment]
@navneetset @Furq07 Is this something for you two to take a gander at?

**Comment by Jmalta101** [comment]
Tested this extension on the 1.20.1 dev server and deleted and uploaded a downloaded one from the site. Issue is persistent as this a extension is owned by @navneetset can you take a look :)

**Comment by Jmalta101** [comment]
This has been fixed now, please close.
