### ISSUE TITLE
Alolan Marowak Type Issue

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#22]
Feature: Alolan Marowak

Expected Behaviour: Supposed to be Fire/Ghost Type

Current Behaviour: Uses base/non-Alolan Marowak's stats | Stats do not match
(Mon belongs to another player)

![Screenshot 2023-11-04 at 3 57 14 PM](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/b1619016-a269-46d9-a4bf-a6c0a348a613)
![Screenshot 2023-11-04 at 3 58 42 PM](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/8feb5534-7aa5-434c-8847-5566be5f4c14)

**Comment by V-lpen** [comment]
Will be fixed soon, thanks for the heads up. It's specifically because it's a shiny marowak. Mon itself is not Alolan, is just a normal shiny marowak.

**Comment by Adainish** [comment]
@V-lpen Did you manage to get a fix for this through yet?

**Comment by V-lpen** [comment]
Waiting on furq but yes can be marked as done
