### ISSUE TITLE
Cubone Quest Not Giving Rewards

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#24]
Feature: Cubone Quest

Expected Behaviour: On completion (up to 10 times) player should obtain a cubone bone.

Current Behaviour: Player reports show that even with enough inventory space, they often don't get rewarded a bone. (Only affects bone reward, not keys after 10 completions)

**Comment by Jmalta101** [comment]
I completed the quest and received all the intended rewards, could not replicate marking this as resolved.
