### ISSUE TITLE
CobbledHunts - Cross-realm functionality 

### ISSUE THREAD

**Issue by Jmalta101** [Cobblemon-Islands/Bugs-And-Issues#25]
Feature: CobbledHunts

Expected Behaviour: Hunt target should go cross-realm, once target is captured(all parameters met) it should mark it complete and give me the reward. 

Current Behaviour: Hunt targets are per-server which means I have 4 different hunts in 4 different servers (hub, star, moon and sun) 

Video Recordings/Screenshots: (HUB) Prior to initiating a hunt >
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/6c0aa664-c707-4e7d-93d9-b97009c53bbe)

(HUB) After initiating a hunt > 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/d90ca9ce-ab15-444b-b0e2-3b4ea4fd699d)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/9f64a26e-73d6-41be-b585-979caf697bc4)

(SUN) After initiating a hunt > 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/b840d855-5cf4-499a-8859-3397897cb617)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/41c76a54-413f-4ed4-9a2f-d30bd5346bc3)

How to reproduce the bug:

**Comment by Adainish** [comment]
Are all servers connected to the same database?

**Comment by Jmalta101** [comment]
In this case Hub and Sun realm are connected to the same database. It seems that they are overwriting each other but remain active until one server has a change.

**Comment by Adainish** [comment]
resolved
