### ISSUE TITLE
CobbledPokeDex - Out of order

### ISSUE THREAD

**Issue by Jmalta101** [Cobblemon-Islands/Bugs-And-Issues#26]
Feature: CobbledPokeDex

Expected Behaviour: Pokedex should be in order by pokedex number.

Current Behaviour: Some pokemons are in order then not. 

Video Recordings/Screenshots:
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/cf9c6481-c946-4e12-aa0c-79719cbb9601)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/55035841/5a55777d-3ab7-4ff1-bec2-037f3eb7bb9f)

How to reproduce the bug:

**Comment by Adainish** [comment]
Discovered to be a datapack error

**Comment by V-lpen** [comment]
fixed
