### ISSUE TITLE
Tpa Broken (Moon?)

### ISSUE THREAD

**Issue by Lysbell** [Cobblemon-Islands/Bugs-And-Issues#27]
Feature: TPA
Expected Behaviour: Getting the Notification that it got accepted and getting Teleported
Current Behaviour: Don't get a Notification and won't getting teleported
Video Recordings/Screenshots:
Additional Notes: Was on Moon Realm, but also happened on Spawn. Relogging fix's it till i change realm or teleport again.

**Comment by Jmalta101** [comment]
Verified all connection's are correct. 

Issue seems to be resolved, please mark as closed.
