### ISSUE TITLE
Commands not working/not being apply for Mods

### ISSUE THREAD

**Issue by Erikasha** [Cobblemon-Islands/Bugs-And-Issues#32]
Feature: Commands that are available for Mods

Expected Behaviour: "/socialsppy command should allow to se Private messages from server chat. 
                                 "/playtime command to check playtime from players

Current Behaviour: "/socialspy shows "You dont have permission to do that"
                               "/playtime show "You dont have permission to do that"

Video Recordings/Screenshots: 

How to reproduce the bug: Being a Mod. Using the command in any real including Hub

**Comment by Jmalta101** [comment]
The new command for socialspy is replaced with /spychat 

Playtime permission has been added to all mods+
