### ISSUE TITLE
Gen2 Crate Gives Regular Totodile Instead of Big Totodile

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#35]
Feature: Gen2 Crate

Expected Behaviour: Unboxing Big Totodile gives cooresponding Big Plush

Current Behaviour: Gives regular plush

(Issue occured with other players as well)
<img width="609" alt="Screenshot 2023-11-13 at 7 09 21 PM" src="https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/fdea24ab-a18a-4aeb-8f3f-cec78915ce38">
<img width="348" alt="Screenshot 2023-11-13 at 7 09 33 PM" src="https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/766c7cdb-1a33-42cf-827f-cfe674adbda5">

**Comment by DZtheCasual** [comment]
Fixed by diablo
