### ISSUE TITLE
Hisuian_Zoroark breaking battle sequence

### ISSUE THREAD

**Issue by Kelgio** [Cobblemon-Islands/Bugs-And-Issues#39]
Feature: Hisuian Zoroark
Expected behavior: player should be able to use it during battles
Current behavior: Hisuian Zoroark won't come out, instead another pokemon from the player's team will and at the same time Hisuian Zoroark would faint.
Evidence: 
https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/151370056/d8e797b3-64d3-4b5d-9c4a-de9652eb60a1

How to reproduce:
1. Have Hisuian Zoroark in the team
2. Send it out during a battle

**Comment by V-lpen** [comment]
Known bug with Cobblemon and the Illusion ability. affects Zorua, Zoroark, hisuian Zorua, and hisuian zoroark.
Unfortunately nothing we can do right now as far as Im aware.

**Comment by Adainish** [comment]
Added to my to-do list

**Comment by V-lpen** [comment]
temporarily fixed by giving Run-Away ability to Zoura and Zoroark. 
Will be reverted back to Illusion when a better fix is done by Adain or Cobblemon.
