### ISSUE TITLE
World Map Overwriting itself everytime when joining a different realm (SUN/MOON)

### ISSUE THREAD

**Issue by Maxello1** [Cobblemon-Islands/Bugs-And-Issues#4]
Feature: Xaeros Minimap/world map
Expected Behaviour: Only showing the current realms map 
Current Behaviour: Overwriting the Last joined realms map

**Comment by Adainish** [comment]
This is a behavioural conflict on the client, as the players connected to a proxy. This is something we can't fix. Maybe contact the Xaeros devs
