### ISSUE TITLE
Shiny Decidueye has broken textures

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#41]
Self-explanatory

<img width="113" alt="Screenshot 2023-11-24 at 12 58 16 AM" src="https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/d0c1ed42-f9da-4d17-8bd6-f3a3c1abdaad">
<img width="342" alt="Screenshot 2023-11-24 at 12 57 04 AM" src="https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/a69ad827-c61f-4256-8e9e-a7b3937ed446">

Reported by player, tested myself, it's just the shiny.

**Comment by V-lpen** [comment]
Fixed! Update to the resourcepack should be pushed tomorrow.

**Comment by RensArtPark** [comment]
Will close as resolved then!
