### ISSUE TITLE
Hisuian Lilligant stats not correct when evolved

### ISSUE THREAD

**Issue by DZtheCasual** [Cobblemon-Islands/Bugs-And-Issues#45]
Feature: Evolution
Expected Behavior: Hisuian Liligant to have correct Base Stats when evolved
Current Behavior: Evolving Petilil gives it normal Liligant stats
![2023-12-08_07 29 20](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/150404624/717112e4-a7ef-4647-a330-240d781ab6f1)
How to reproduce: Evolve Petilil into Hisuian Liligant using 2 Sun Stones

**Comment by DZtheCasual** [comment]
Note: Giving it with command /pokegive lilligant hisuian will work
Also /pokegift fixed its stats as well

**Comment by V-lpen** [comment]
I believe this is just a simple visual glitch. Can you confirm if it fixes after evolving a petilil and relogging? 

> Note: Giving it with command /pokegive lilligant hisuian will work Also /pokegift fixed its stats as well
