### ISSUE TITLE
Nether Deletes Pokemon Party

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#46]
As reported by Geek and Luna

Feature: Nether + Party

Expected Behaviour: Mons sync and do not delete

Current Behaviour: Mons in player's party delete when in nether and leaving 

Video Recordings/Screenshots:

![image-4](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/e27c27ee-fb13-44cb-8a8a-ba310407cdd0)
![image-5](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/149705850/a0c58be0-c7cb-440b-9ac7-2d1241174153)

**Comment by Furqit** [comment]
This was Resolved!
