### ISSUE TITLE
Pokeclear/Pokewipe

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#49]
Feature: Pokeclear/Pokewipe
Expected Behaviour: Clears Pokemon that are not in battle, or Legendary/Mythical, or Shiny(?)
Current Behaviour: Clears all pokemon (Except your own) regardless of if you're in battle, a legendary, shiny, or mythical.
Video Recordings/Screenshots: N/A
Additional Notes: --I believe it's a known issue, just porting it to here--

**Comment by Adainish** [comment]
A fix has been pushed, will need to be implemented by the system admins

**Comment by RealCarrotDev** [comment]
@Adainish This is happening again, but it seems to only be happening in Star realm.

Happened with a Kyogre yesterday [User isn't part of discord so we didn't know until today]

**Comment by Adainish** [comment]
@Furq07 will need to update and fix the config
