### ISSUE TITLE
Feebas Evolving without scale

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#52]
Feature: Feebas Evolution
Expected Behaviour: Requires dragon scale to evolve
Current Behaviour: Does not require dragon scale to evolve
Video Recordings/Screenshots: N/A 
Additional Notes:

**Comment by V-lpen** [comment]
Feebas should require the prism scale to evolve
https://gitlab.com/cable-mc/cobblemon/-/blob/main/common/src/main/resources/data/cobblemon/species/generation3/feebas.json

**Comment by V-lpen** [comment]
Close please, prism scale trade evolution is correct as far as I am aware
