### ISSUE TITLE
Poke Keys not stacking due to different names

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#53]
Feature: Crate Keys / Names
Expected Behaviour: To be able to stack and to keep the same name
Current Behaviour: Different names continually from Voting and from loot chests
Video Recordings/Screenshots:
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/6016440f-ff4c-43cf-a9e3-dae090f0579a)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/a211de9b-ede4-4f46-ab62-7512131b0877)

Additional Notes:

**Comment by Furqit** [comment]
Hmm, can you tell me the source of them, how did you got the different names one?

**Comment by RealCarrotDev** [comment]
Voting crates and loot chests are different names

**Comment by Furqit** [comment]
ah gotcha, will get that fixed.

**Comment by V-lpen** [comment]
should be fixed
