### ISSUE TITLE
Items Mispelled / Names

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#54]
Feature: Item Names
Expected Behaviour: Spelled correctly
Current Behaviour: Mispelled / Name order is wrong(?)
Video Recordings/Screenshots: 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/1d553dcd-fe2a-447c-94ba-09856098a3a5)
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/3f8154e6-a371-4e53-9a3c-b35696d66ef8)

Additional Notes:  You can see Fennekin is spelled incorrectly - I haven't looked through every single item (yet), just a small adjustment to fix the name!

Also - The plushies are sometimes called, "Pokemonnamehere Plushie" and then others "Plushie Pokemonnamehere"

This should be extremely low priority.

**Comment by Furqit** [comment]
This was fixed.
