### ISSUE TITLE
Outbreak Pokemon stop spawning after Pokewipe

### ISSUE THREAD

**Issue by devUmbra** [Cobblemon-Islands/Bugs-And-Issues#57]
Feature: Pokemon Outbreaks
Expected Behaviour: Outbreaks continue after a pokemon wipe happens
Current Behaviour: All outbreak pokemon get wiped (this is fine) but stop spawning afterwards
Additional Info: incident happened in star realm

**Comment by Adainish** [comment]
Need Additional testing for more info

**Comment by Adainish** [comment]
After testing it turns out that it wasn't a bug but the max configured spawn capacity of 32 for the entire outbreak being hit. Preventing further spawns
