### ISSUE TITLE
Claimblocks Going Into Negatives 

### ISSUE THREAD

**Issue by RensArtPark** [Cobblemon-Islands/Bugs-And-Issues#58]
Feature: Claimblocks

Expected Behaviour: Claimblocks stay synced across realms and remain useable as long as players have an appropriate amount.

Current Behaviour: Players using claimtool are shown to have blocks in the negatives no matter how many they owned previously

Unsure how to reproduce, Umbra noted "Going to spawn and back into a realm fixed it for a few minutes"

**Comment by devUmbra** [comment]
Some players also experienced not gaining any claimblocks at all. Even after hours of playing per session, their claimblock count didnt increase.

**Comment by RealCarrotDev** [comment]
Adding onto this - unclaiming/abandoning a claim will reproduce this issue as well. 

Some people are also experiencing increase in blocks in different realms.

**Comment by Furqit** [comment]
This issue was fixed.
