### ISSUE TITLE
Scraggy and Scrafty Party frames

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#60]
Feature: Party Frame for Scraggy and Scrafty
Expected Behaviour: To be centered like the rest
Current Behaviour: Out of frame barely showing the pokemon
Video Recordings/Screenshots: 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/732ccf7f-661f-4a6a-9958-61d079ece86f)

**Comment by V-lpen** [comment]
Will be fixed soon! Gonna go through and correct a bunch of poser positions.
