### ISSUE TITLE
End Last legend

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#63]
Feature: /Lastlegend in END
Expected Behaviour: To show when the last legend was killed/captured
Current Behaviour: Does nothing in the END
Video Recordings/Screenshots:

https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/32a470ed-6946-4eae-a28b-a7e4601ea51a

Additional Notes: Works in all other realms/nether.

**Comment by Furqit** [comment]
@Hiimiko is this still a issue? I think this was fixed.
