### ISSUE TITLE
Shaders & Custom Armor

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#64]
Feature: Custom Armor
Expected Behaviour: Custom armor to be displayed properly even with shaders on
Current Behaviour: Custom armor glitches out and looks like a bunch of lines/etc when shaders are turned on
Video Recordings/Screenshots: 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/5771c78b-d641-4bbc-b8f1-3321ba4630c8)
With shaders

and then without 

![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/05c663ec-387e-4bae-977e-c2b21bf42101)

Additional Notes: Diablo knows about this, just putting it in here for records sake

**Comment by Furqit** [comment]
You need to Install Forge CIT in your client mods for that to work.

**Comment by Furqit** [comment]
@Adainish feel free to close this issue.
