### ISSUE TITLE
Nether Legends Spawning into Lava

### ISSUE THREAD

**Issue by DZtheCasual** [Cobblemon-Islands/Bugs-And-Issues#65]
Feature: Nether Legendary Spawn

Expected Behaviour: Spawn Legends in a safe enough spot for people to have a chance at catching them

Current Behaviour: Nether Legends often spawn in Lava under a player and usually dies before a player has a chance to catch them

Video Recordings/Screenshots:
https://youtu.be/qmmlPH0UPUU 

How to Reproduce: not 100% sure as it kinda just happens.

**Comment by V-lpen** [comment]
Made most fire legendaries fire resistant! If i missed one, let me know.
