### ISSUE TITLE
Permanent Shoulder Buff

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#66]
Feature: Shoulder Buffs
Expected Behaviour: Give buff only when on shoulder
Current Behaviour: Permanent buff until logout
Video Recordings/Screenshots: 

https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/425b9d11-d3d6-4a80-a5a2-c5643f58f4e6

Additional Notes: Happens with Espurr, and Skitty, possibly more (Will update if I find more)
Can confirm is a server only issue, won't let you shoulder these mons in singleplayer on modpack.

**Comment by V-lpen** [comment]
https://modrinth.com/datapack/cobble-cats

Must be from this. I shall investigate soon!

**Comment by V-lpen** [comment]
Fixed
