### ISSUE TITLE
Skiddo Model Broken

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#74]
Feature: Pokemon Model for Skiddo

Expected Behaviour: Not broken

Current Behaviour: Is broken / missing textures

![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/08ccd2d4-6e0f-44d3-a91c-ff6bfd6196a4)

**Comment by RealCarrotDev** [comment]
Additional Notes: Gogoat is broken too - 
![image](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/de099753-85e0-47f7-bc38-b4891074d72f)

**Comment by V-lpen** [comment]
Fixed, will be applied to the server soon!
