### ISSUE TITLE
Pikachu not evolving

### ISSUE THREAD

**Issue by RealCarrotDev** [Cobblemon-Islands/Bugs-And-Issues#76]
Feature: Evolution

Expected Behaviour: Using Thunderstone on Pikachu to evolve it to Raichu

Current Behaviour: Pikachu not evolving when using stone

https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/11451708/8e7f271c-629f-4bad-b8d5-721ebb8bbb9f

**Comment by V-lpen** [comment]
Cobblemon bug :(
