### ISSUE TITLE
Pokecoins not rewarding on Kill (SUN-Realm)

### ISSUE THREAD

**Issue by Maxello1** [Cobblemon-Islands/Bugs-And-Issues#8]
Feature: Pokecoins
Expected Behaviour: Player gets rewarded x Amount of Coins for defeating a pokemon
Current Behaviour: Player does not get the pokecoins in Sun realm
Video Recordings/Screenshots:
Additional Notes:

**Comment by Adainish** [comment]
Jar might need swapping if this hasn't been fixed yet @Furq07

**Comment by Jmalta101** [comment]
Could not replicate, ensured all realms have the same mechanic and no issues. 
Please mark as resolved.
