### ISSUE TITLE
Cosmetic infinite dupe bug 

### ISSUE THREAD

**Issue by Deckersche** [Cobblemon-Islands/Bugs-And-Issues#85]
Having a Cosmetic equiped on your head (Alolan Vulpix Hat for example) allowes you to do /hat with any other random block. After doing so the Cosmetic u wore gets put in your inventory. That item you can redeem, sell etc. This is infinitely repeatable.

**Comment by sysdm1** [comment]
A fix has been put in place and will be put on live.

**Comment by Adainish** [comment]
Resolved thanks to @sysdm-del
