### ISSUE TITLE
Players getting random cosmetics unlocked and locked even tho never having them 

### ISSUE THREAD

**Issue by Deckersche** [Cobblemon-Islands/Bugs-And-Issues#86]
The reason why is unknown up until now seems random. Happened to like 3 people who got sets unlocked they didnt even have and then locked again and then unlocked again. 
![2024-01-17_16 38 44](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/156931370/47aa67b7-a282-452f-a5cf-15cbe10884aa)
Remix doesnt own any of those Cosmetics. But server gave them to him somehow.

**Comment by sysdm1** [comment]
This has been fixed. Was a conflict with Arclight.
