### ISSUE TITLE
Pokebuilder command broken

### ISSUE THREAD

**Issue by DorkyAF** [Cobblemon-Islands/Bugs-And-Issues#91]
Feature: /Pokebuilder

Expected Behaviour: Opens the Pokebuilder menu

Current Behaviour: Error message appearing in chat instead

Video Recordings/Screenshots:
![image (3)](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/156593734/01dc6c05-1762-4395-93b6-dca7205ec367)

**Comment by Adainish** [comment]
Fixed, player data got corrupted
