### ISSUE TITLE
Grimmsnarl Hat Unredeemable

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#93]
Feature: [Cosmetics - Grimmsnarl Hat]

Expected Behaviour: [Redeem Grimmsnarl Hat]

Current Behaviour: [Unredeemable]

Video Recordings/Screenshots: N/A

How to reproduce the bug: N/A - Cannot recreate as I do not have said item.

**Comment by DZtheCasual** [comment]
Its only to old redeemable cosmetics. A new one just needs to be spawned in
