### ISSUE TITLE
Possible Torterra walking animation problem

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#96]
Feature: [Cobblemon Model Animations]

Expected Behaviour: [Torterra able to walk]

Current Behaviour: [Standing still]

Video Recordings/Screenshots:
![Screenshot 2024-01-23 044026](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/b4e6016c-1d92-4861-baea-e69374d62f2a)

https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/d8446d92-3b0d-47e0-85cf-417f13c54e97

**Comment by V-lpen** [comment]
Kind of a Cobblemon thing, as far as i know
