### ISSUE TITLE
Tympole Line Name Error

### ISSUE THREAD

**Issue by Cathaldhus** [Cobblemon-Islands/Bugs-And-Issues#99]
Feature: [Tympole Line Names] (unsure about seismitoad)

Expected Behaviour: [Spelled Properly (could be a format thing?)]

Current Behaviour: [Not spelled properly]

Video Recordings/Screenshots:
![tympole name](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/15bae6dc-f97c-492f-b3a9-e667b9eab06d)
![Screenshot 2024-01-24 234235](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/157429050/f0ab81a9-d0de-49b7-9d76-ba9ccb2d105c)

**Comment by V-lpen** [comment]
Unable to replicate? Non-issue?

**Comment by Cathaldhus** [comment]
Very weird. Must be a visual thing. Thank you I'll inform.
